version: 0.2

phases:
  install:
    commands:
      - echo "Downloading and installing Terraform..."
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      # - sudo yum install -y yum-utils shadow-utils
      # - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      # - sudo yum -y install terraform
      - terraform --version  # Verify Terraform installation

  
  pre_build:
    commands:
      - echo "Terraform execution started on `date`"
      - echo "Current working directory $(pwd)"
      - ls -la

  build:
    commands:
      - echo "Copying backend configuration"
      - cp $ENV_DIR/backend.tf .
      - ls
      # - terraform force-unlock a14fcffe-524d-1c08-ff7b-f5685708933d
      #- terraform force-unlock -force 6696fdb8-316b-c8b0-ebf4-e971cc6ea9b8
      # - aws s3 rm s3://pw-s3-terraform-backend/dev/infra-microservices/terraform.tfstate
      # - aws dynamodb scan --table-name pw_dynamodb_terraform_statelock
      
      # - aws eks list-clusters --region us-east-1 --role-arn arn:aws:iam::767397709508:role/pw-role-dev-crossaccount_infra_role
      # - aws eks get-token --cluster-name pw-eks-cluster-dev --region us-east-1 --role-arn arn:aws:iam::767397709508:role/pw-role-dev-crossaccount_infra_role
      # - aws sts get-caller-identity --role-arn arn:aws:iam::767397709508:role/pw-role-dev-crossaccount_infra_role
      # - aws eks update-kubeconfig --region us-east-1 --name pw-eks-cluster-dev --role-arn arn:aws:iam::767397709508:role/pw-role-dev-crossaccount_infra_role 

      # - aws eks update-kubeconfig --region us-east-1 --name pw-eks-cluster-dev --role-arn arn:aws:iam::767397709508:role/pw-role-dev-crossaccount_infra_role

      # - aws eks --region us-east-1 update-kubeconfig --name pw-eks-cluster-dev --role-arn arn:aws:iam::767397709508:role/pw-role-dev-crossaccount_infra_role

      - terraform init
      # - terraform force-unlock -force a14fcffe-524d-1c08-ff7b-f5685708933d

      - terraform plan -var-file=$ENV_DIR/terraform.tfvars -out=tfplan
      # - terraform destroy -var-file=$ENV_DIR/terraform.tfvars -auto-approve 

      #- terraform show -json tfplan > tfplan.json
      - echo "Contents of current directory:"
      - ls -la
      #- echo "Contents of tfplan.json:"
      #- cat tfplan.json | head -n 20

artifacts:
  files:
    - $ENV_DIR/**/*
  name: terraform-plan-output